#----------------------------------------
#Created by Serhii Zubenko 2023
#----------------------------------------

name: GitHub_Action_Copart

on: 
  push:
      branches:
      - master

jobs: 
  smoke_tests: 
    runs-on: ubuntu-latest

    steps:
    - name: print  a Hello message
      run:  echo "Hello Serhii"
    - name: clone Git repository
      run:  action/checkout@github.com:SerhiiZubenko/Copart.git
    



